name: reqres_app
description: Reqress App
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_secure_storage: ^9.0.0
  dio: ^5.3.2
  

dev_dependencies:
  flutter_lints: ^2.0.0
  talker_dio_logger: ^1.3.0
  
flutter:

  uses-material-design: true